/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Checks that the API can reach the database.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The database is reachable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
                /** @description The database is not reachable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example unavailable */
                            status: string;
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Creates a user and returns an access/refresh token pair, the same as /auth/login. Rate-limited per client IP (shared with /auth/login); see the 429 response.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description "cookie" for browser clients that keep the refresh token in the httpOnly cookie only: the response body then leaves refresh_token out, so a script injected in the page can't read it. */
                    "X-Refresh-Token-Transport"?: components["parameters"]["RefreshTokenTransport"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Missing/invalid email, or password shorter than 8 characters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Returns an access/refresh token pair. Rate-limited per client IP (shared with /auth/register); see the 429 response.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description "cookie" for browser clients that keep the refresh token in the httpOnly cookie only: the response body then leaves refresh_token out, so a script injected in the page can't read it. */
                    "X-Refresh-Token-Transport"?: components["parameters"]["RefreshTokenTransport"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Invalid email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair
         * @description The submitted refresh token is single-use: a successful call revokes it and returns a new one. Reusing an already-rotated refresh token is treated as a possible theft and revokes every refresh token for that user, so all of that user's other sessions are also logged out. Exception: a token rotated out less than 10 seconds ago, whose replacement is still valid, is accepted once more (the client most likely never received the response). The token is read from the JSON body, or, when the body has none, from the tamiyo_refresh_token cookie (browser clients send an empty body).
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description "cookie" for browser clients that keep the refresh token in the httpOnly cookie only: the response body then leaves refresh_token out, so a script injected in the page can't read it. */
                    "X-Refresh-Token-Transport"?: components["parameters"]["RefreshTokenTransport"];
                };
                path?: never;
                cookie?: {
                    /** @description Refresh token set by /auth/register, /auth/login and /auth/refresh. Used when the request body carries no refresh_token. */
                    tamiyo_refresh_token?: components["parameters"]["RefreshCookie"];
                };
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Refresh token in neither the body nor the cookie, or malformed body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid, expired, or already-used refresh token (the refresh cookie is cleared) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revokes the given refresh token so it can no longer be used to obtain new access tokens. Idempotent: logging out with an unknown or already-revoked refresh token still returns 204. Note this does not invalidate an access token already issued — it simply expires on its own shortly after (see JWT_ACCESS_TOKEN_TTL_MINUTES). The token is read from the JSON body, or from the tamiyo_refresh_token cookie when the body has none. The refresh cookie is always cleared.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    /** @description Refresh token set by /auth/register, /auth/login and /auth/refresh. Used when the request body carries no refresh_token. */
                    tamiyo_refresh_token?: components["parameters"]["RefreshCookie"];
                };
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Refresh token in neither the body nor the cookie, or malformed body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the authenticated user's password
         * @description Requires the current password. On success, every refresh token belonging to the user is revoked — other sessions must log in again.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing current_password, or new_password shorter than 8 characters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing/invalid access token, or current_password is incorrect. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User no longer exists */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Always responds 204, whether or not the email belongs to an account — this prevents an attacker from using the endpoint to discover which emails are registered. When the account exists, a single-use reset token is emailed to it (valid for PASSWORD_RESET_TOKEN_TTL_MINUTES, 30 minutes by default). Shares the same rate limiter as /auth/register and /auth/login.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid email */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a password using a token from the forgot-password email
         * @description Consumes a single-use reset token and sets a new password. On success, every refresh token belonging to the account is revoked — all other sessions must log in again, same as /auth/password.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing token, or new_password shorter than 8 characters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid, expired, or already-used reset token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cards
         * @description List the authenticated user's cards, with optional filtering and pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Only return cards belonging to this storage. */
                    storage_id?: number;
                    /** @description Case-insensitive partial match on the card name. */
                    name?: string;
                    /** @description Only return cards whose color identity fits inside these colors (e.g. a commander's identity), in any order. An empty value keeps colorless cards only. Cards whose color identity isn't known yet are left out. */
                    color_identity?: string;
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Number of cards per page (max 100). */
                    limit?: number;
                    /** @description Sort field, with an optional "-" prefix for descending order. id is always used as a secondary tie-breaker for a stable order. */
                    sort?: "name" | "-name" | "added" | "-added" | "updated" | "-updated" | "mana_value" | "-mana_value" | "color" | "-color" | "type" | "-type";
                    /** @description Return one entry per stack of identical copies (same printing, foil and storage) instead of one per card. Each entry is the stack's lowest-id copy with quantity and copy_ids set; total, page and limit then count stacks. added is the oldest copy's, updated the most recent one's. */
                    stack?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedCards"];
                    };
                };
                /** @description storage_id, page or limit is invalid, or sort is not one of the allowed values. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a card */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCardRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Missing required field, invalid UUID, invalid collector_number, or storage_id does not reference an existing storage owned by the authenticated user. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Delete every card of the account
         * @description Deletes all of the authenticated user's cards at once: they are removed from every deck, and any deck whose commander was one of them has its commander_id cleared. Storages and decks themselves are kept. Requires confirm=true, so the collection can't be wiped by accident.
         */
        delete: {
            parameters: {
                query: {
                    /** @description Must be true. */
                    confirm: true;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteAllCardsResponse"];
                    };
                };
                /** @description confirm=true is missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/refresh-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fill in missing colors and types from Scryfall
         * @description Looks up on Scryfall every card of the account whose colors or card_type aren't known yet (cards created before they were stored, or imported while Scryfall was unreachable), and stores its colors, primary type and mana value. Works through at most 750 cards per call, in id order, so a call stays short: while next_after_id is not null, call again with after_id set to it.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Only look at cards with a greater id (the next_after_id of the previous call). */
                    after_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailsRefreshSummary"];
                    };
                };
                /** @description after_id is not a non-negative integer */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
                502: components["responses"]["BadGateway"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: components["parameters"]["CardID"];
            };
            cookie?: never;
        };
        /** Get a card by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Card ID */
                    id: components["parameters"]["CardID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Card not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a card
         * @description Removes the card from any deck it belongs to, and clears commander_id on any deck where it was the commander.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Card ID */
                    id: components["parameters"]["CardID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Card not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Partially update a card
         * @description Only the fields present in the body are modified. added and updated can never be changed after creation.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Card ID */
                    id: components["parameters"]["CardID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Invalid id, invalid body, invalid scryfall_id, or storage_id does not reference an existing storage owned by the authenticated user. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Card not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List storages
         * @description List the authenticated user's storages, with optional filtering and pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Only return storages whose type exactly matches (case-insensitive). */
                    type?: string;
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Number of storages per page (max 100). */
                    limit?: number;
                    /** @description Sort field, with an optional "-" prefix for descending order. id is always used as a secondary tie-breaker for a stable order. */
                    sort?: "name" | "-name" | "added" | "-added" | "updated" | "-updated";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedStorages"];
                    };
                };
                /** @description page or limit is invalid, or sort is not one of the allowed values. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a storage */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStorageRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Storage"];
                    };
                };
                /** @description Missing required field */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: components["parameters"]["StorageID"];
            };
            cookie?: never;
        };
        /** Get a storage by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Storage ID */
                    id: components["parameters"]["StorageID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Storage"];
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Storage not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a storage
         * @description Any card currently in this storage has its storage_id set to null. Cards are never deleted as a side effect.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Storage ID */
                    id: components["parameters"]["StorageID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Storage not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Partially update a storage */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Storage ID */
                    id: components["parameters"]["StorageID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStorageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Storage"];
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Storage not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List decks
         * @description List the authenticated user's decks, with optional filtering and pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Only return decks whose format exactly matches (case-insensitive). */
                    format?: string;
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Number of decks per page (max 100). */
                    limit?: number;
                    /** @description Sort field, with an optional "-" prefix for descending order. id is always used as a secondary tie-breaker for a stable order. */
                    sort?: "name" | "-name" | "added" | "-added" | "updated" | "-updated";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedDecks"];
                    };
                };
                /** @description page or limit is invalid, or sort is not one of the allowed values. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a deck */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDeckRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deck"];
                    };
                };
                /** @description Missing required field, or commander_id does not reference an existing card owned by the authenticated user. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        /** Get a deck by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deck"];
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a deck
         * @description Removes all card_deck associations for this deck. Cards themselves are never deleted.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Partially update a deck */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDeckRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deck"];
                    };
                };
                /** @description Invalid id, invalid body, or invalid commander_id. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deck/{id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        /** List the cards in a deck */
        get: {
            parameters: {
                query?: {
                    /** @description Sort field, with an optional "-" prefix for descending order. id is always used as a secondary tie-breaker for a stable order. */
                    sort?: "name" | "-name" | "added" | "-added" | "updated" | "-updated" | "mana_value" | "-mana_value";
                };
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (empty array if the deck has no cards) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"][];
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
                /** @description Card ID */
                card_id: components["parameters"]["CardIDPath"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Add a card to a deck
         * @description Idempotent: calling this again with the same id/card_id succeeds silently if the card is already in the deck.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                    /** @description Card ID */
                    card_id: components["parameters"]["CardIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description id or card_id is not a valid integer */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found or card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        post?: never;
        /**
         * Remove a card from a deck
         * @description Idempotent: always succeeds, whether or not the card was actually linked to the deck, or whether the deck/card exist at all. The guaranteed end state is "this card is not in this deck".
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                    /** @description Card ID */
                    card_id: components["parameters"]["CardIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description id or card_id is not a valid integer */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        /** List the cards waiting to be added to the collection for this deck */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (empty array when nothing is pending) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingCard"][];
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Add a card to the deck's pending list */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddPendingCardRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingCard"];
                    };
                };
                /** @description Invalid id or body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}/pending/{pending_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
                /** @description Pending card ID */
                pending_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a card from the deck's pending list */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                    /** @description Pending card ID */
                    pending_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Deck or pending card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}/pending/commit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the pending cards in the collection and put them in the deck */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        storage_id?: number | null;
                        /** @description Only add this pending card (all its copies) instead of the whole list. */
                        pending_id?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingCommitSummary"];
                    };
                };
                /** @description Invalid id or body, or storage_id doesn't reference an existing storage */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}/legality": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        /**
         * Check a deck's legality for its own format
         * @description Checks every card in the deck against the deck's own format field, using each card's Scryfall legalities. For the "commander" format specifically, also checks singleton (one copy of each card by name, basic lands excepted) and color identity (every card within the commander's color identity). Nothing is persisted — computed fresh from Scryfall data on every call.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LegalityReport"];
                    };
                };
                /** @description id is not a valid integer, or the deck's format isn't one Scryfall recognizes. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
                502: components["responses"]["BadGateway"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deck/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        /**
         * Summarize a deck's composition
         * @description Mana curve, color breakdown and primary card types, computed from Scryfall data. Lands are excluded from the mana curve, color breakdown and average mana value, but still counted in card_count, land_count and type_breakdown.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeckStats"];
                    };
                };
                /** @description id is not a valid integer, or the deck's format isn't one Scryfall recognizes. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
                502: components["responses"]["BadGateway"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/manabox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk import a ManaBox collection export
         * @description Imports a ManaBox_Collection.csv export. For each row, gets or creates the matching storage (Binder Name/Binder Type), gets or creates a deck too if Binder Type is "deck" (format defaults to "commander" — correct it afterwards with PATCH /deck/:id if needed), creates one card per physical copy (Quantity), and links deck cards accordingly. The export already carries the Scryfall ID directly, so this route never calls Scryfall and never returns 502.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The ManaBox_Collection.csv file. Required columns: Binder Name, Binder Type, Name, Set code, Scryfall ID, Collector number, Foil, Quantity (order doesn't matter).
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Import finished (possibly with some rows skipped — see ImportSummary.warnings). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportSummary"];
                    };
                };
                /** @description No file field, or the file couldn't be parsed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/moxfield/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk import a Moxfield collection export
         * @description Imports a Moxfield "Export Collection" CSV. Moxfield's export has no storage concept, so every created card is assigned to the existing storage given by storage_id. It also has no Scryfall ID, so each row is resolved by (set, collector number) against the Scryfall API (https://scryfall.com/docs/api/cards/collection).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The Moxfield collection CSV export. Required columns: Count, Name, Edition, Foil, Collector Number (order doesn't matter).
                         */
                        file: string;
                        /** @description Must reference an existing storage for this account. */
                        storage_id: number;
                    };
                };
            };
            responses: {
                /** @description Import finished (possibly with some rows skipped — see ImportSummary.warnings). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportSummary"];
                    };
                };
                /** @description No file field, the file couldn't be parsed, or storage_id does not reference an existing storage. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
                502: components["responses"]["BadGateway"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/moxfield/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk import a Moxfield deck export
         * @description Imports a Moxfield deck's plain-text export (deck page -> More -> Export -> Plain Text). Creates one new deck and one card per physical copy listed, linked to it. Each line is resolved by (set, collector number) against Scryfall, same as the collection route. The plain-text format has no section headers, so by convention the first line is treated as the commander unless commander_from_first_line is set to false; an unresolvable commander is skipped (counted in cards_skipped) and the deck is still created without one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The deck's plain-text export. Each line looks like "1 Sol Ring (SLD) 1011 *F*".
                         */
                        file: string;
                        /** @description The new deck's name — the file itself doesn't carry one. */
                        name: string;
                        /** @description The new deck's format (e.g. commander, modern). */
                        format: string;
                        /**
                         * @description Treat the first card line as the deck's commander.
                         * @default true
                         */
                        commander_from_first_line?: boolean;
                        /** @description Must reference an existing storage for this account if provided. Left unset, imported cards have no storage. */
                        storage_id?: number;
                    };
                };
            };
            responses: {
                /** @description Import finished (possibly with some rows skipped — see ImportSummary.warnings). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportSummary"];
                    };
                };
                /** @description Missing file/name/format, the file couldn't be parsed, commander_from_first_line or storage_id is invalid, or storage_id does not reference an existing storage. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
                502: components["responses"]["BadGateway"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/manabox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the collection as a ManaBox CSV
         * @description Exports the account's entire collection as a ManaBox-compatible CSV (ManaBox_Collection_export.csv), matching the columns POST /import/manabox reads. Identical physical copies within the same storage collapse into one row with a Quantity. Cards are grouped by storage (ManaBox's only organizing concept); a card with no storage is grouped under a synthetic "Unsorted" binder rather than dropped. A card's deck membership is tracked independently of storage in Tamiyo and isn't reflected here — only a storage whose own type is "deck" is exported as Binder Type "deck".
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The CSV file, served as a download. */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/moxfield/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the collection as a Moxfield collection CSV
         * @description Exports the account's entire collection as a Moxfield-compatible "Export Collection" CSV, matching the columns POST /import/moxfield/collection reads. Identical physical copies collapse into one row with a Count. Moxfield's format has no storage concept, so — unlike the ManaBox export — cards are grouped across every storage (and unsorted cards) without distinction.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The CSV file, served as a download. */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/moxfield/deck/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck ID */
                id: components["parameters"]["DeckID"];
            };
            cookie?: never;
        };
        /**
         * Export one deck as a Moxfield deck plain-text export
         * @description Exports one deck (not the whole collection) as a Moxfield deck plain-text export, matching the format POST /import/moxfield/deck reads: one line per distinct printing. If the deck has a commander, that printing's line (with its full quantity in the deck) is written first, so re-importing the file reconstructs the same commander via the usual "first line" convention. A deck with no commander has no special first line — every line is sorted alphabetically.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Deck ID */
                    id: components["parameters"]["DeckID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The deck's plain-text export, served as a download. */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                400: components["responses"]["InvalidID"];
                401: components["responses"]["Unauthorized"];
                /** @description Deck not found, or not owned by the authenticated user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LegalityIssue: {
            card_id?: number;
            card_name: string;
            reason: string;
        };
        LegalityReport: {
            format: string;
            legal: boolean;
            issues?: components["schemas"]["LegalityIssue"][];
        };
        ManaCurveBucket: {
            mana_value: number;
            count: number;
        };
        DeckStats: {
            card_count: number;
            land_count: number;
            nonland_count: number;
            average_mana_value: number;
            mana_curve: components["schemas"]["ManaCurveBucket"][];
            color_breakdown: {
                [key: string]: number;
            };
            type_breakdown: {
                [key: string]: number;
            };
        };
        Error: {
            error: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenPair: {
            /** @description Short-lived JWT access token. Send as "Authorization: Bearer <token>". */
            token: string;
            /** @description Long-lived opaque token. Send to /auth/refresh to obtain a new token pair, or to /auth/logout to end this session. Omitted when the request sent "X-Refresh-Token-Transport: cookie": the token is then only in the tamiyo_refresh_token cookie. */
            refresh_token?: string;
        };
        RefreshRequest: {
            /** @description Optional when the tamiyo_refresh_token cookie is sent. */
            refresh_token?: string;
        };
        LogoutRequest: {
            /** @description Optional when the tamiyo_refresh_token cookie is sent. */
            refresh_token?: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            new_password: string;
        };
        Card: {
            id: number;
            name: string;
            /** Format: uuid */
            scryfall_id: string;
            set_code: string;
            collector_number: string;
            foil: boolean;
            storage_id?: number | null;
            /** @description Converted mana cost (CMC). */
            mana_value: number;
            /** @description The card's colors as WUBRG letters in that order ("WR" for a Boros card), empty for a colorless card, null when not known yet (see POST /cards/refresh-details). */
            colors?: string | null;
            /**
             * @description Primary type, from the type line (lands first, then creatures, planeswalkers...). null when not known yet.
             * @enum {string|null}
             */
            card_type?: "Creature" | "Planeswalker" | "Battle" | "Instant" | "Sorcery" | "Artifact" | "Enchantment" | "Land" | "Other" | null;
            /** @description Color identity as WUBRG letters in that order, empty for a colorless card, null when not known yet (see POST /cards/refresh-details). */
            color_identity?: string | null;
            added: string;
            updated: string;
            /** @description Only with GET /cards?stack=true, the number of copies in the stack. */
            quantity?: number;
            /** @description Only with GET /cards?stack=true, the ids of the stack's copies, lowest first. */
            copy_ids?: number[];
        };
        PendingCard: {
            id: number;
            deck_id: number;
            name: string;
            /** Format: uuid */
            scryfall_id: string;
            set_code: string;
            collector_number: string;
            foil: boolean;
            quantity: number;
            mana_value: number;
            colors?: string | null;
            /** @enum {string|null} */
            card_type?: "Creature" | "Planeswalker" | "Battle" | "Instant" | "Sorcery" | "Artifact" | "Enchantment" | "Land" | "Other" | null;
            color_identity?: string | null;
            added: string;
        };
        AddPendingCardRequest: {
            name: string;
            /** Format: uuid */
            scryfall_id: string;
            set_code: string;
            collector_number: string;
            foil?: boolean;
            /** @default 1 */
            quantity?: number;
            mana_value?: number;
            colors?: string | null;
            /** @enum {string|null} */
            card_type?: "Creature" | "Planeswalker" | "Battle" | "Instant" | "Sorcery" | "Artifact" | "Enchantment" | "Land" | "Other" | null;
            color_identity?: string | null;
        };
        PendingCommitSummary: {
            cards_created: number;
        };
        DetailsRefreshSummary: {
            /** @description Cards whose details were filled in. */
            updated: number;
            /** @description Cards Scryfall didn't know (their details stay unknown). */
            not_found: number;
            /** @description Cards still missing details after this batch. */
            remaining: number;
            /** @description after_id to send on the next call, null when there is nothing left. */
            next_after_id: number | null;
        };
        DeleteAllCardsResponse: {
            /** @description Number of cards deleted. */
            deleted: number;
        };
        PaginatedCards: {
            data: components["schemas"]["Card"][];
            page: number;
            limit: number;
            total: number;
            total_pages: number;
        };
        CreateCardRequest: {
            name: string;
            /** Format: uuid */
            scryfall_id: string;
            set_code: string;
            collector_number: string;
            /** @default false */
            foil: boolean;
            storage_id?: number | null;
            /**
             * @description Converted mana cost (CMC). Not fetched automatically from Scryfall — supplied by the client, same as name or set_code.
             * @default 0
             */
            mana_value: number;
            /** @description WUBRG letters (any case and order, normalized to WUBRG order), empty for colorless. Optional: left unknown when omitted. */
            colors?: string | null;
            /**
             * @description Primary type. Optional, left unknown when omitted.
             * @enum {string|null}
             */
            card_type?: "Creature" | "Planeswalker" | "Battle" | "Instant" | "Sorcery" | "Artifact" | "Enchantment" | "Land" | "Other" | null;
            /** @description WUBRG letters (any case and order, normalized to WUBRG order), empty for colorless. Optional: left unknown when omitted. */
            color_identity?: string | null;
        };
        /** @description All fields optional; only included fields are modified. */
        UpdateCardRequest: {
            name?: string;
            /** Format: uuid */
            scryfall_id?: string;
            set_code?: string;
            collector_number?: string;
            foil?: boolean;
            /** @description Moves the card to this storage. null removes the card from its storage; leaving the field out keeps the current one. */
            storage_id?: number | null;
            mana_value?: number;
            colors?: string;
            /** @enum {string} */
            card_type?: "Creature" | "Planeswalker" | "Battle" | "Instant" | "Sorcery" | "Artifact" | "Enchantment" | "Land" | "Other";
            color_identity?: string;
        };
        Storage: {
            id: number;
            name: string;
            type: string;
            card_count: number;
            added: string;
            updated: string;
        };
        PaginatedStorages: {
            data: components["schemas"]["Storage"][];
            page: number;
            limit: number;
            total: number;
            total_pages: number;
        };
        CreateStorageRequest: {
            name: string;
            type: string;
        };
        /** @description All fields optional; only included fields are modified. */
        UpdateStorageRequest: {
            name?: string;
            type?: string;
        };
        Deck: {
            id: number;
            name: string;
            format: string;
            commander_id?: number | null;
            /** @description The commander when it's one of the deck's pending cards (not in the collection yet). At most one of commander_id and commander_pending_id is set. */
            commander_pending_id?: number | null;
            /**
             * Format: uuid
             * @description Scryfall id of the printing whose art (art_crop) is shown behind the deck, null when none was chosen.
             */
            background_scryfall_id?: string | null;
            /**
             * Format: uuid
             * @description Scryfall id of the commander card, null without a commander.
             */
            readonly commander_scryfall_id?: string | null;
            card_count: number;
            /** @description Copies waiting in the deck's pending list (not in the collection yet), not counted in card_count. */
            pending_count?: number;
            added: string;
            updated: string;
        };
        PaginatedDecks: {
            data: components["schemas"]["Deck"][];
            page: number;
            limit: number;
            total: number;
            total_pages: number;
        };
        CreateDeckRequest: {
            name: string;
            format: string;
            commander_id?: number;
            /** Format: uuid */
            background_scryfall_id?: string;
        };
        /** @description All fields optional; only included fields are modified. */
        UpdateDeckRequest: {
            name?: string;
            format?: string;
            commander_id?: number;
            /** @description Make one of the deck's pending cards the commander (clears commander_id). Setting commander_id clears it in turn. */
            commander_pending_id?: number;
            /** @description Set to true to explicitly clear commander_id (set it to null). */
            clear_commander_id?: boolean;
            /** Format: uuid */
            background_scryfall_id?: string;
            /** @description Set to true to remove the chosen art (set background_scryfall_id to null). */
            clear_background_scryfall_id?: boolean;
        };
        /** @description Result of a bulk import. A malformed or unresolvable row never aborts the whole import — it's recorded as a skipped card with a warning instead. */
        ImportSummary: {
            cards_created?: number;
            cards_skipped?: number;
            storages_created?: number;
            decks_created?: number;
            /** @description Omitted entirely when there are no warnings. */
            warnings?: string[];
        };
    };
    responses: {
        /** @description id is not a valid integer */
        InvalidID: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server/database error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or expired access token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests from this client IP on /auth/register, /auth/login, and /auth/forgot-password combined (AUTH_RATE_LIMIT_MAX per AUTH_RATE_LIMIT_WINDOW_SECONDS, 5 per 60s by default). A Retry-After header (seconds) indicates when to retry. */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the rate limit window resets. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A bulk import couldn't reach or parse a response from the Scryfall API while resolving Moxfield rows. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description "cookie" for browser clients that keep the refresh token in the httpOnly cookie only: the response body then leaves refresh_token out, so a script injected in the page can't read it. */
        RefreshTokenTransport: "cookie";
        /** @description Refresh token set by /auth/register, /auth/login and /auth/refresh. Used when the request body carries no refresh_token. */
        RefreshCookie: string;
        /** @description Card ID */
        CardID: number;
        /** @description Storage ID */
        StorageID: number;
        /** @description Deck ID */
        DeckID: number;
        /** @description Card ID */
        CardIDPath: number;
    };
    requestBodies: never;
    headers: {
        /** @description tamiyo_refresh_token=<refresh token>; HttpOnly; SameSite=Strict; Secure (unless REFRESH_COOKIE_SECURE=false); Path=<API_BASE_PATH>/auth; Max-Age = JWT_REFRESH_TOKEN_TTL_DAYS. Lets a browser client keep the refresh token out of reach of JavaScript. */
        RefreshCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
